### ISSUE TITLE
refactor to k8s-style resources

### ISSUE THREAD

**Issue by ssube** [ssube/isolex#24]
Resources follow somewhat standard forms, but mix and match standard fields with configuration. This leads to complex types (some impossible to enforce) and endless reserved names. Kubernetes fixed this quite cleanly:

```yaml
metadata:
  apiVersion: v1
  kind: Pod
  name: foo
  labels:
    bar: a
    bin: b
data:
  # actual body
```

Breaking out the metadata will allow easy definition of service definitions, better registration, and eventually tagging. It should also ease nesting and linking.

This will be a large refactor and needs to:

- [x] add `Transform` services
  - [x] wire up to controllers
- [x] refactor `Command` (these are commands, not objects)
  - [x] `name` to `noun`
  - [x] `type` to `verb`
- [x] standardize some junk:
  - [x] `Config` vs `Data` naming
  - [x] `emit` config block (partial `Command`)
  - [ ] `msg`/`msgs` vs `message`/`messages`
  - [x] other naming issues
- [x] document naming conventions
  
- [ ] figure out:
  - [ ] tracking services from `Context` (any service that interacted with it?)
