### ISSUE TITLE
matchers and rules

### ISSUE THREAD

**Issue by ssube** [ssube/isolex#31]
### Summary

In order to implement conditional transforms, select anything by label, or implement rule-based filters, we need matchers and rules.

Take [an example of a pod that uses pod affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - S1
        topologyKey: failure-domain.beta.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security
              operator: In
              values:
              - S2
          topologyKey: kubernetes.io/hostname
```

This provides a weighted set of rules to match data (in this case, labels). Revising that slightly with isolex terminology:

```yaml
metadata:
  kind: template-transform
  name: with-pod-affinity
  scope: foo
data:
  matches:
    - key: security
      operator: In
      values:
        - S1
```

### Scope

- [x] config schema
- [x] matching utility class
  - [x] `string` matches
  - [x] `regex` matches
  - [x] `every` operator
  - [x] `any` operator
  - [x] `negate` flag

### Use Case

1. Matching labels
1. Conditional transforms
1. Filtering messages
1. Everything else with rules

### Issues

Total rabbit hole. Implement operators as needed.

### Details

Should be a utility class and some operators.
