### ISSUE TITLE
add service test scenarios

### ISSUE THREAD

**Issue by ssube** [ssube/isolex#486]
# Feature

The most effective tests launch a bot or a few services in-memory and send them some messages/commands, then test the result. Those are easily described in YAML documents like:

```yaml
scenarios:
  - name: test-foo
    services: []
    inputs: []
    outputs: []
```

These should be executed by the script generator.
